// <auto-generated />
using System;
using ECT.ACC.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECT.ACC.Data.Migrations
{
    [DbContext(typeof(ECTDbContext))]
    [Migration("20260304015545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECT.ACC.Data.Models.DeficitAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassificationNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DeficitType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId")
                        .IsUnique();

                    b.ToTable("DeficitAnalyses");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId")
                        .IsUnique();

                    b.ToTable("ScenarioParameters");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.DeficitAnalysis", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.Scenario", "Scenario")
                        .WithOne("DeficitAnalysis")
                        .HasForeignKey("ECT.ACC.Data.Models.DeficitAnalysis", "ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "CAvailable", b1 =>
                        {
                            b1.Property<int>("DeficitAnalysisId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("CAvailableCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("CAvailableExponent");

                            b1.HasKey("DeficitAnalysisId");

                            b1.ToTable("DeficitAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("DeficitAnalysisId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "CDeficit", b1 =>
                        {
                            b1.Property<int>("DeficitAnalysisId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("CDeficitCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("CDeficitExponent");

                            b1.HasKey("DeficitAnalysisId");

                            b1.ToTable("DeficitAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("DeficitAnalysisId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "CRequired", b1 =>
                        {
                            b1.Property<int>("DeficitAnalysisId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("CRequiredCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("CRequiredExponent");

                            b1.HasKey("DeficitAnalysisId");

                            b1.ToTable("DeficitAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("DeficitAnalysisId");
                        });

                    b.Navigation("CAvailable")
                        .IsRequired();

                    b.Navigation("CDeficit")
                        .IsRequired();

                    b.Navigation("CRequired")
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioParameters", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.Scenario", "Scenario")
                        .WithOne("Parameters")
                        .HasForeignKey("ECT.ACC.Data.Models.ScenarioParameters", "ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "Complexity", b1 =>
                        {
                            b1.Property<int>("ScenarioParametersId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("ComplexityCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("ComplexityExponent");

                            b1.HasKey("ScenarioParametersId");

                            b1.ToTable("ScenarioParameters");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioParametersId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "Control", b1 =>
                        {
                            b1.Property<int>("ScenarioParametersId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("ControlCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("ControlExponent");

                            b1.HasKey("ScenarioParametersId");

                            b1.ToTable("ScenarioParameters");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioParametersId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "Energy", b1 =>
                        {
                            b1.Property<int>("ScenarioParametersId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("EnergyCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("EnergyExponent");

                            b1.HasKey("ScenarioParametersId");

                            b1.ToTable("ScenarioParameters");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioParametersId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "TimeAvailable", b1 =>
                        {
                            b1.Property<int>("ScenarioParametersId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("TimeAvailableCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("TimeAvailableExponent");

                            b1.HasKey("ScenarioParametersId");

                            b1.ToTable("ScenarioParameters");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioParametersId");
                        });

                    b.Navigation("Complexity")
                        .IsRequired();

                    b.Navigation("Control")
                        .IsRequired();

                    b.Navigation("Energy")
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("TimeAvailable")
                        .IsRequired();
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.Scenario", b =>
                {
                    b.Navigation("DeficitAnalysis");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
