// <auto-generated />
using System;
using ECT.ACC.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECT.ACC.Data.Migrations
{
    [DbContext(typeof(ECTDbContext))]
    [Migration("20260316070927_AddScenarioSolveForAndMode")]
    partial class AddScenarioSolveForAndMode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECT.ACC.Data.Models.DeficitAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassificationNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("DeficitType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId")
                        .IsUnique()
                        .HasFilter("[ConfigurationId] IS NOT NULL");

                    b.HasIndex("ScenarioId");

                    b.ToTable("DeficitAnalyses");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsEctCoreParameter")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "Key")
                        .IsUnique();

                    b.ToTable("ParameterDefinitions");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterDocumentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DerivationNarrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "ParameterKey")
                        .IsUnique();

                    b.ToTable("ParameterDocumentations");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ProcessDomainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDomainId");

                    b.ToTable("ParameterTemplates");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ParameterDocumentationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParameterDocumentationId");

                    b.ToTable("ParameterVariants");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ProcessDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("ProcessDomains");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ProcessDomainId")
                        .HasColumnType("int");

                    b.Property<string>("ScenarioMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Flat");

                    b.Property<string>("SolveForMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("C");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDomainId");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioConfigurations");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioConfigurationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("ParameterKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VariantId")
                        .HasColumnType("int");

                    b.Property<string>("VariantLabel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("Base");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId", "ParameterKey")
                        .IsUnique();

                    b.ToTable("ScenarioConfigurationEntries");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScenarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId")
                        .IsUnique();

                    b.ToTable("ScenarioParameters");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.SubParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Operation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ParameterDocumentationId")
                        .HasColumnType("int");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterDocumentationId");

                    b.ToTable("SubParameters");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.TemplateParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultUnit")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsEctCoreParameter")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ParameterTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterTemplateId");

                    b.ToTable("TemplateParameterDefinitions");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.VariantSubParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Operation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ParameterVariantId")
                        .HasColumnType("int");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ParameterVariantId");

                    b.ToTable("VariantSubParameters");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.DeficitAnalysis", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.ScenarioConfiguration", "Configuration")
                        .WithOne("DeficitAnalysis")
                        .HasForeignKey("ECT.ACC.Data.Models.DeficitAnalysis", "ConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ECT.ACC.Data.Models.Scenario", "Scenario")
                        .WithMany("DeficitAnalyses")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "CAvailable", b1 =>
                        {
                            b1.Property<int>("DeficitAnalysisId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("CAvailableCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("CAvailableExponent");

                            b1.HasKey("DeficitAnalysisId");

                            b1.ToTable("DeficitAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("DeficitAnalysisId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "CDeficit", b1 =>
                        {
                            b1.Property<int>("DeficitAnalysisId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("CDeficitCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("CDeficitExponent");

                            b1.HasKey("DeficitAnalysisId");

                            b1.ToTable("DeficitAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("DeficitAnalysisId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "CRequired", b1 =>
                        {
                            b1.Property<int>("DeficitAnalysisId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("CRequiredCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("CRequiredExponent");

                            b1.HasKey("DeficitAnalysisId");

                            b1.ToTable("DeficitAnalyses");

                            b1.WithOwner()
                                .HasForeignKey("DeficitAnalysisId");
                        });

                    b.Navigation("CAvailable")
                        .IsRequired();

                    b.Navigation("CDeficit")
                        .IsRequired();

                    b.Navigation("CRequired")
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterDefinition", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.Scenario", "Scenario")
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValueOwned", "DefaultValue", b1 =>
                        {
                            b1.Property<int>("ParameterDefinitionId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("DefaultValue_Coefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("DefaultValue_Exponent");

                            b1.HasKey("ParameterDefinitionId");

                            b1.ToTable("ParameterDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ParameterDefinitionId");
                        });

                    b.Navigation("DefaultValue");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterDocumentation", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.Scenario", "Scenario")
                        .WithMany("ParameterDocumentations")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterTemplate", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.ProcessDomain", "ProcessDomain")
                        .WithMany("Templates")
                        .HasForeignKey("ProcessDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDomain");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterVariant", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.ParameterDocumentation", "ParameterDocumentation")
                        .WithMany("Variants")
                        .HasForeignKey("ParameterDocumentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParameterDocumentation");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.Scenario", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.ProcessDomain", "ProcessDomain")
                        .WithMany("Scenarios")
                        .HasForeignKey("ProcessDomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProcessDomain");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioConfiguration", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioConfigurationEntry", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.ScenarioConfiguration", "Configuration")
                        .WithMany("Entries")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValueOwned", "SnapshotValue", b1 =>
                        {
                            b1.Property<int>("ScenarioConfigurationEntryId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("SnapshotCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("SnapshotExponent");

                            b1.HasKey("ScenarioConfigurationEntryId");

                            b1.ToTable("ScenarioConfigurationEntries");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioConfigurationEntryId");
                        });

                    b.Navigation("Configuration");

                    b.Navigation("SnapshotValue");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioParameters", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.Scenario", "Scenario")
                        .WithOne("Parameters")
                        .HasForeignKey("ECT.ACC.Data.Models.ScenarioParameters", "ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "Complexity", b1 =>
                        {
                            b1.Property<int>("ScenarioParametersId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("ComplexityCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("ComplexityExponent");

                            b1.HasKey("ScenarioParametersId");

                            b1.ToTable("ScenarioParameters");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioParametersId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "Control", b1 =>
                        {
                            b1.Property<int>("ScenarioParametersId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("ControlCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("ControlExponent");

                            b1.HasKey("ScenarioParametersId");

                            b1.ToTable("ScenarioParameters");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioParametersId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "Energy", b1 =>
                        {
                            b1.Property<int>("ScenarioParametersId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("EnergyCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("EnergyExponent");

                            b1.HasKey("ScenarioParametersId");

                            b1.ToTable("ScenarioParameters");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioParametersId");
                        });

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValue", "TimeAvailable", b1 =>
                        {
                            b1.Property<int>("ScenarioParametersId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("TimeAvailableCoefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("TimeAvailableExponent");

                            b1.HasKey("ScenarioParametersId");

                            b1.ToTable("ScenarioParameters");

                            b1.WithOwner()
                                .HasForeignKey("ScenarioParametersId");
                        });

                    b.Navigation("Complexity")
                        .IsRequired();

                    b.Navigation("Control")
                        .IsRequired();

                    b.Navigation("Energy")
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("TimeAvailable")
                        .IsRequired();
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.SubParameter", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.ParameterDocumentation", "ParameterDocumentation")
                        .WithMany("SubParameters")
                        .HasForeignKey("ParameterDocumentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValueOwned", "Value", b1 =>
                        {
                            b1.Property<int>("SubParameterId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("Value_Coefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("Value_Exponent");

                            b1.HasKey("SubParameterId");

                            b1.ToTable("SubParameters");

                            b1.WithOwner()
                                .HasForeignKey("SubParameterId");
                        });

                    b.Navigation("ParameterDocumentation");

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.TemplateParameterDefinition", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.ParameterTemplate", "ParameterTemplate")
                        .WithMany("ParameterDefinitions")
                        .HasForeignKey("ParameterTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValueOwned", "SeedValue", b1 =>
                        {
                            b1.Property<int>("TemplateParameterDefinitionId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("SeedValue_Coefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("SeedValue_Exponent");

                            b1.HasKey("TemplateParameterDefinitionId");

                            b1.ToTable("TemplateParameterDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("TemplateParameterDefinitionId");
                        });

                    b.Navigation("ParameterTemplate");

                    b.Navigation("SeedValue");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.VariantSubParameter", b =>
                {
                    b.HasOne("ECT.ACC.Data.Models.ParameterVariant", "ParameterVariant")
                        .WithMany("SubParameters")
                        .HasForeignKey("ParameterVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ECT.ACC.Data.Math.ScientificValueOwned", "Value", b1 =>
                        {
                            b1.Property<int>("VariantSubParameterId")
                                .HasColumnType("int");

                            b1.Property<double>("Coefficient")
                                .HasColumnType("float")
                                .HasColumnName("Value_Coefficient");

                            b1.Property<double>("Exponent")
                                .HasColumnType("float")
                                .HasColumnName("Value_Exponent");

                            b1.HasKey("VariantSubParameterId");

                            b1.ToTable("VariantSubParameters");

                            b1.WithOwner()
                                .HasForeignKey("VariantSubParameterId");
                        });

                    b.Navigation("ParameterVariant");

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterDocumentation", b =>
                {
                    b.Navigation("SubParameters");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterTemplate", b =>
                {
                    b.Navigation("ParameterDefinitions");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ParameterVariant", b =>
                {
                    b.Navigation("SubParameters");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ProcessDomain", b =>
                {
                    b.Navigation("Scenarios");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.Scenario", b =>
                {
                    b.Navigation("DeficitAnalyses");

                    b.Navigation("ParameterDefinitions");

                    b.Navigation("ParameterDocumentations");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("ECT.ACC.Data.Models.ScenarioConfiguration", b =>
                {
                    b.Navigation("DeficitAnalysis");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
